version: v1.0.0.{build}
os: Visual Studio 2015

init:
- cmd: >-
    choco install dotnetcore -version 1.0.0.001598

    set PATH=C:\Program Files\dotnet\bin;%PATH%
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: 1.0.0.{build}
  assembly_file_version: 1.0.0.{build}
  assembly_informational_version: 1.0.0-alpha-{build}
before_build:
- cmd: >-
    dotnet restore src\ImageProcessorCore

    cd build

    npm install

    node appveyor-project-version-patch.js

    cd..

build_script:
- cmd: >-
     dotnet pack src\ImageProcessorCore --configuration Release --output "artifacts\bin\ImageProcessorCore"

test: off
artifacts:
- path: artifacts\bin\ImageProcessorCore\**\*.nupkg